#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

TOMCAT_DIR="$OPENSHIFT_DATA_DIR/apache-tomcat-8.0.33"

#Deploy application
#Killing running process
#echo "Killing current java process"
#ps -ef | grep java| grep -v grep | awk '{print $2}' | xargs kill
#cd $TOMCAT_DIR/bin
#./shutdown.sh

javac -version

cd $OPENSHIFT_DATA_DIR
echo -e  "<settings>\n <localRepository>$OPENSHIFT_DATA_DIR</localRepository>\n</settings>\n" > settings.xml

cd $OPENSHIFT_REPO_DIR
$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn -f $OPENSHIFT_REPO_DIR/pom.xml -s $OPENSHIFT_DATA_DIR/settings.xml -DskipTests=true clean install -P openshift
#war=`ls webapps/*.war | awk -F'/' '{print $2}'`


#mkdir $TOMCAT_DIR/webapps
#cp webapps/$war $TOMCAT_DIR/webapps/ROOT.war
# nohup java -jar $OPENSHIFT_REPO_DIR/target/.jar > $LOG 2>&1 &

rm -rf $TOMCAT_DIR/work/Catalina/shop-venkatvp.rhcloud.com
rm -rf $TOMCAT_DIR/webapps/ROOT
rm -rf $TOMCAT_DIR/logs/*
#Cleanup to gain disk space
rm -rf $OPENSHIFT_REPO_DIR/node
rm -rf $OPENSHIFT_REPO_DIR/node_modules


export JAVA_OPTS=-Dspring.profiles.active=openshift

cd $TOMCAT_DIR/bin
echo starting tomcat with $JAVA_OPTS
./startup.sh
