#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_65" 
export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_65/bin:$PATH
cd $OPENSHIFT_DATA_DIR/apache-tomcat-8.0.33/bin
./startup.sh